---
title: "fa_models"
format: html
embed-resources: true
editor: visual
---

```{r, echo=FALSE}
#| echo: FALSE

library(haven)
library(ggplot2)
library(dplyr)
library(knitr)
library(psych)

ud_all = readRDS("./synthetic_cidi.rds")

G_max <- 10
G_seq <- seq(G_max)

bigcolumnnames <- c("Age at first episode of depression", "Age at last episode of depression", "Ever had prolonged feelings of sadness or depression", "Ever had prolonged loss of interest in normal activities", "Depression possibly related to stressful or traumatic event", "Fraction of day affected during worst episode of depression", "Frequency of depressed days during worst episode of depression", "Brightening of mood in response to positive events during worst episode of depression", "Time of day that mood was worse during worst episode of depression", "Feelings of tiredness during worst episode of depression", "Feelings of heaviness in limbs during worst episode of depression", "Change in appetite during worst episode of depression", "Sleep changed during sadness/depression or loss of interest", "Trouble falling asleep", "Waking too early", "Sleeping too much", "Difficulty concentrating during worst depression", "Feelings of worthlessness during worst period of depression", "Feelings of guilt during worst period of depression", "Thoughts of death during worst depression", "Duration of worst depression", "Impact on normal roles during worst period of depression", "Difficult coping with rejection or negative responses", "Lifetime number of depressed periods", "Weight gain during worst period of depression", "Weight loss during worst period of depression")


```

```{r}
#| echo: FALSE

print_max_factors <- function(fa.model, columnnames, G_model){

    for(j in seq(G_model)){
      print(paste(j, " of ", G_model))
      maxcolumnnames_j <- columnnames[max.col(abs(fa.model$weights))==j]
      maxcolumnsigns_j <- sign(fa.model$weights[,j])[max.col(abs(fa.model$weights))==j]
      maxcolumnvalues_j <- fa.model$weights[,j][max.col(abs(fa.model$weights))==j]

     # print(maxcolumnnames_j)
    #  print(maxcolumnsigns_j)
      
      print(t(rbind(maxcolumnnames_j, t(maxcolumnsigns_j), t(signif(maxcolumnvalues_j,4)))))
    }
    
}

plot_BIC_from_fa <- function(model, G_min, G_max){
  vec.BIC <- vector()
  for(i in seq(G_min,G_max)){
    vec.BIC <- append(vec.BIC,model[[i]]$BIC)
  }
  
  plot(seq(G_min,G_max),vec.BIC)
  plot(seq(G_min,G_max - 1),diff(vec.BIC,differences = 1))
  plot(seq(G_min,G_max - 2),diff(vec.BIC,differences = 2))
  
}

plot_BIC_from_fa_list <- function(model_list, G_min, G_max){
  plot.data <- data.frame(metric = double(), G = integer(), method = character())
  method_names = c("mixed", "pearson", "kendall", "spearman")
  n <- length(model_list)
  for(j in seq(n)){
      vec.BIC <- vector()
  for(i in seq(G_min,G_max)){
    vec.BIC <- append(vec.BIC,model[[i]]$BIC)
  }
      
  plot.data <- rbind(plot.data, data.frame(vec.BIC, seq(G_min, G_max), rep(method_names[[j]], G_max-G_min)))
  
  }
  
  plot(seq(G_min,G_max),vec.BIC)
  plot(seq(G_min,G_max - 1),diff(vec.BIC,differences = 1))
  plot(seq(G_min,G_max - 2),diff(vec.BIC,differences = 2))
  
}

```

You can add options to executable code like this

```{r}
#| echo: FALSE

mixed.cor.all <- readRDS(file = paste("./2022_fitted_models_v3/mixed.cor.all.rds",sep=""))

pearson.cor.all <- readRDS(file = paste("./2022_fitted_models_v3/pearson.cor.all.rds",sep=""))

kendall.cor.all <- readRDS(file = paste("./2022_fitted_models_v3/kendall.cor.all.rds",sep=""))

spearman.cor.all <- readRDS(file = paste("./2022_fitted_models_v3/spearman.cor.all.rds",sep=""))

heatmap(mixed.cor.all, Rowv = NA, Colv = NA)

heatmap(pearson.cor.all, Rowv = NA, Colv = NA)

heatmap(kendall.cor.all, Rowv = NA, Colv = NA)

heatmap(spearman.cor.all, Rowv = NA, Colv = NA)


```

The `echo: false` option disables the printing of code (only output is displayed).

```{r}
#| echo: FALSE

all.mixed.list <- readRDS(file = "./2022_fitted_models_v3/m.fa.all.2022.mixed.list.rds")
all.pearson.list <- readRDS(file = "./2022_fitted_models_v3/m.fa.all.2022.pearson.list.rds")
all.kendall.list <- readRDS(file = "./2022_fitted_models_v3/m.fa.all.2022.kendall.list.rds")
all.spearman.list <- readRDS(file = "./2022_fitted_models_v3/m.fa.all.2022.spearman.list.rds")

```

```{r}
#| echo: FALSE

list.all.lists <- list(all.mixed.list, all.pearson.list, all.kendall.list, all.spearman.list)

list.all.cors <- list(mixed.cor.all, pearson.cor.all, kendall.cor.all, spearman.cor.all)

```

```{r}
#| echo: FALSE

plot_metrics_comparison_from_fa <- function(list.of.lists,G_max,metric_name,pop_name, log.metric=TRUE){

  plot.data <- data.frame(metric = double(), G = integer(), method = character())
  method_names = c("mixed", "pearson", "kendall", "spearman")

  for(j in seq(4)){
      vec.metric <- vector()
  for(i in seq(G_max)){
    if(metric_name=="RMSEA"){
      vec.entry <- list.of.lists[[j]][[i]][[metric_name]][1]
    } else if(metric_name=="CFI"){
      vec.entry <- 1 - max(0,list.of.lists[[j]][[i]][[metric_name]])
    } else {
      vec.entry <- list.of.lists[[j]][[i]][[metric_name]]
    }
    
    if (is.null(vec.entry)){
      vec.metric <- append(vec.metric, NA)
    }else{
      vec.metric <- append(vec.metric, vec.entry)
    }
    
  }
  plot.data <- rbind(plot.data, data.frame(metric = vec.metric, G = seq(G_max), method = rep(method_names[[j]], G_max)))
  
  }

    plot_title <- paste(metric_name,"for",pop_name,sep=" ")
    if(log.metric){
      plot_title <- paste("log scale",plot_title, sep= " ")
    }
    ggplot(plot.data, aes(x = G, y = metric)) +
    geom_point(aes(colour = method)) +
    theme_minimal() +
    ggtitle(plot_title) + 
    labs(x = "K") + 
    scale_x_continuous(breaks = seq(10)) +
    {if(log.metric)scale_y_continuous(transform = "log10")}
  
}
```

```{r}
#| echo: FALSE

method_names = c("mixed", "pearson", "kendall", "spearman")
metric_names = c("RMSEA", "rms", "BIC", "EBIC", "CFI")
metric_names = c("STATISTIC", "RMSEA", "rms", "BIC", "EBIC", "CFI")
pop_names = c("all")
#pop_names = c("all")

G_max <- 10
for(metric_name in metric_names){
    print(plot_metrics_comparison_from_fa(list.all.lists,G_max,metric_name, "all", log.metric=FALSE))
    print(plot_metrics_comparison_from_fa(list.all.lists,G_max,metric_name, "all", log.metric=TRUE))
}

```

```{r}
#| echo: FALSE

for(j in seq(4)){
  scree(list.all.cors[[j]])
}

```

```{r}
#| echo: FALSE
#| eval: FALSE

  for(j in seq(4)){
    for(G_here in seq(G_max)){
      print(method_names[j])
      print_max_factors(list.all.lists[[j]][[G_here]],bigcolumnnames,G_here)
    }
  }

```

```{r}
#| echo: FALSE
#| output: asis

get_max_factors <- function(fa.model, columnnames, G_model, method_name){
  
    assignment <- data.frame(variables=columnnames,assignment=max.col(abs(fa.model$weights)), method_name=method_name)
    return(assignment)
}

match_max_factors <- function(list_max_factor, G_max){
  resultstable <- data.frame(variables = list_max_factor[[1]]$variables)
  for (j in seq(G_max)){
    resultstable[,as.character(j)] <- ""
  }
  
  for(mfa in list_max_factor){
    for(j in seq(dim(mfa)[1])){
      resultstable[j,mfa[j,]$assignment+1] <- paste(resultstable[j,mfa[j,]$assignment + 1], mfa[j,]$method_name,sep="")
    }
  }
  
  return(resultstable)
}
method_codes <- c("M", "P", "K", "S")
i<-3
for (G_here in seq(5)){
  list_max_factors <- list()
for(j in seq(4)){
  list_max_factors[[j]] <- get_max_factors(list.all.lists[[j]][[G_here]],bigcolumnnames,G_here, method_codes[j])
}

resultstable <- match_max_factors(list_max_factors, G_here)
print(kable(resultstable))
}


```
